### ISSUE TITLE
few improvements

### ISSUE THREAD

**Issue by HongChenTW** [kiedveian/JDExam#1]
Hi @kiedveian, I'm Hong from Trend Micro, thanks for your work and there are few improvement suggestions:

1. According to the command hint, `--help` flag seems not working.
2. Consider making command (e.g. linecount) as constant variable in your switch statements and hint, it will be easier for maintenance.
3. [unit test] Consider making 1 function which needed to be tested for 1 test function, with this implementation, you will be easier to expand, refine or add new test cases against various conditions.

cc @cheyilin

**Comment by HongChenTW** [comment]
Hi @kiedveian, I've noticed you have started pushing improvements for this issue, if you're ready for review, please leave comments in this issue.

If you have any questions or feedback, feel free to let me know, thanks!

**Comment by kiedveian** [comment]
Hi @HongChenTW, I'm ready for review.

**Comment by HongChenTW** [comment]
Thanks for the improvements, here is some suggestions:

1. variable name should be more precisely

Ex. 

```go
FlagLineCount    = "linecount"
```

should be like

```go
CmdLineCount    = "linecount"
```

2. The reason using constant variable instead of directly filling value is to follow [Single Source of Truth (SSOT)](https://en.wikipedia.org/wiki/Single_source_of_truth)

>In information systems design and theory, single source of truth (SSOT) is the practice of structuring information models and associated data schema such that every data element is mastered (or edited) in only one place. Any possible linkages to this data element (possibly in other areas of the relational schema or even in distant federated databases) are by reference only.

If your application becomes more and more complex, variables may across various directories with hierarchies, SSOT makes you easier to debug, trace and develop.

I see you have made nearly all strings into constant variables, after finishing the rest I think the issue can be closed:

a. constant variable can also be format variable

Ex.

```go
const (
	linecountString = `Print line count of file
Usage:
  fops linecount [flags]
Flags:
  -f, --file   the input file`
)
```

can be like

```go
const (
        CmdLineCount      = "linecount"
	linecountStringTemplate   = `Print line count of file
Usage:
  fops %s [flags]
Flags:
  -f, --file   the input file`
)

// using
linecountString := fmt.Sprintf(linecountStringTemplate, CmdLineCount)

```

b. there are still some variables remain string
