### ISSUE TITLE
build and publish release in CircleCI pipeline

### ISSUE THREAD

**Issue by rybbchao** [kiedveian/JDExam#4]
Please integrate build process into CircleCI with version tagging for #3.
And also publish a release automatically with built executable

**Comment by rybbchao** [comment]
Hi @kiedveian,

Thanks for your work!
Please feel free to leave comments if you think the code met the requirements.

**Comment by kiedveian** [comment]
> Hi @kiedveian,
> 
> Thanks for your work!
> Please feel free to leave comments if you think the code met the requirements.

There are many same error handler code in test functions.
The one of the improvements I think, merge them to a function.
```
func checkIntResult(t *testing.T, fopsErr *FopsError, data ,ans int){
	if fopsErr != nil {
		t.Errorf(fopsErr.Err.Error())
	} else if data != ans {
		t.Errorf("result: %d , expected: %d ", data, ans)
	}
}
```
But the line number of output in the error message will be change into the "check function" position. So I canceled this change.

**Comment by kiedveian** [comment]
Then, I try to edit the yml file of CircleCI, move golang test to circleci.
This is I first contact with golang, auto build, yml file, and CircleCI.
There are many trial and error in the program. So I still don't understand CircleCI now.
It may use much time.

**Comment by kiedveian** [comment]
Hi @rybbchao, I think the code met the requirements.

**Comment by rybbchao** [comment]
> > Hi @kiedveian,
> > Thanks for your work!
> > Please feel free to leave comments if you think the code met the requirements.
> 
> There are many same error handler code in test functions.
> The one of the improvements I think, merge them to a function.
> 
> ```
> func checkIntResult(t *testing.T, fopsErr *FopsError, data ,ans int){
> 	if fopsErr != nil {
> 		t.Errorf(fopsErr.Err.Error())
> 	} else if data != ans {
> 		t.Errorf("result: %d , expected: %d ", data, ans)
> 	}
> }
> ```
> 
> But the line number of output in the error message will be change into the "check function" position. So I canceled this change.

Try using `Table-Driven` unit tests like as below:

```go
func TestRunCheckSum(t *testing.T) {
	type args struct {
		args []string
	}
	tests := []struct {
		name    string
		args    args
		want    string
		wantErr *FopsError
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := RunCheckSum(tt.args.args)
			if got != tt.want {
				t.Errorf("RunCheckSum() got = %v, want %v", got, tt.want)
			}
			// TODO: Implement function `compareError`
			if !compareError(err, tt.wantErr) {
				t.Errorf("RunCheckSum() err = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
``` 

However, this issue is opened for CircleCI pipeline implementation. If you have any comments for improvement, you could open a new issue or just leave them in the issue #1.

**Comment by rybbchao** [comment]
Reviewed. It's great you added some integration tests. Close now.
